input {
  beats {
    port => 5046
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
      target => "parsed"
      tag_on_failure => "_jsonparsefailure"
    }
  }
}

output {
  elasticsearch {
    hosts => ["es-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}